### ISSUE TITLE
Reachable by Any Means (RAM) states, traces, maybe messages

### ISSUE THREAD

**Issue by traiansf** [runtimeverification/vlsm#58]
Introduce the following definitions and refactor existing code to use them where relevant.

- [x] `ram_state X s := valid_state_prop (pre_loaded_with_all_messages_vlsm X) s`
- [x] `ram_transition X l s im s' om := input_valid_transition (pre_loaded_with_all_messages_vlsm X) l (s, im) (s', om)`
- [x] `ram_trace X s  tr := finite_valid_trace (pre_loaded_with_all_messages_vlsm X) s tr`
      and also for other trace-like definitions
- [ ] `ram_message X m := can_emit  (pre_loaded_with_all_messages_vlsm X) m`

**Comment by wkolowski** [comment]
I don't like the name "Reachable by Any Means" (quite long), and also the abbreviation "RAM" may be confusing to outsiders.
